export const GOVLYX_EMOJIS = [
  "/govlyx-emoji/blush.svg",
  "/govlyx-emoji/heart-eyes.svg",
  "/govlyx-emoji/kissing.svg",
  "/govlyx-emoji/yum.svg",
  "/govlyx-emoji/wink.svg",
  "/govlyx-emoji/tongue.svg",
  "/govlyx-emoji/silly.svg",
  "/govlyx-emoji/sunglasses.svg",
  "/govlyx-emoji/smirk.svg",
  "/govlyx-emoji/relieved.svg",
  "/govlyx-emoji/surprised.svg",
  "/govlyx-emoji/grimace.svg",
  "/govlyx-emoji/worried.svg",
  "/govlyx-emoji/disappointed.svg",
  "/govlyx-emoji/tired.svg",
  "/govlyx-emoji/sleepy.svg",
  "/govlyx-emoji/sob.svg",
  "/govlyx-emoji/heart.svg",
  "/govlyx-emoji/thumbs_up.svg",
  "/govlyx-emoji/thumbs_down.svg",
  "/govlyx-emoji/peace.svg",
  "/govlyx-emoji/wave.svg",
  "/govlyx-emoji/ok_sign.svg",
  "/govlyx-emoji/fist.svg",
  "/govlyx-emoji/point.svg",
  "/govlyx-emoji/clap.svg",
  "/govlyx-emoji/crossed_fingers.svg",
  "/govlyx-emoji/high_five.svg",
  "/govlyx-emoji/govlyx.svg",
  "/govlyx-emoji/govlyx-square.svg",
];

export const STICKERS = GOVLYX_EMOJIS;